### ISSUE TITLE
Error: "Invalid API response from server: type mismatch"

### ISSUE THREAD

**Issue by ktkwon00** [indocomsoft/fluminurs#129]
Running fluminurs.windows.exe gives the following error: 
`Error: "Invalid API response from server: type mismatch"`

Might be a change on LumiNUS' end, as it was working fine 2 days ago.

**Comment by indocomsoft** [comment]
Hi @ktkwon00, I moved this to the correct repository.

Are you able to get Rust toolchain running and run a debug build? The stack trace will be useful here. Otherwise I can provide you with a debug build executable this weekend

**Comment by ktkwon00** [comment]
Sorry for the mistake. It would be great if you could send me a debug build

**Comment by indocomsoft** [comment]
@ktkwon00 can you try using https://github.com/indocomsoft/fluminurs/releases/tag/1.1.4

Hopefully that fixes your crash

**Comment by ktkwon00** [comment]
Thanks for the update. However, I'm experiencing a different error now.
This only occurs when I run fluminurs.windows.exe with --download-to, and does not occur when I run it without any parameters.

`(redacted)\fluminurs>set RUST_BACKTRACE=full

(redacted)\fluminurs>fluminurs.windows.exe --download-to "(redacted)"
Hi KIM TAE KWON!
You are taking:
(redacted)
You are teaching:
Download to (redacted)
Failed loading module files: Unable to deserialize JSON
thread 'main' panicked at 'Children should have been loaded', src\libcore\option.rs:1185:5
stack backtrace:
   0:           0x56ceab - <unknown>
   1:           0x48cf4b - <unknown>
   2:           0x56bf07 - <unknown>
   3:           0x56bbb3 - <unknown>
   4:           0x56b1c6 - <unknown>
   5:           0x570270 - <unknown>
   6:           0x57a569 - <unknown>
   7:           0x48a51d - <unknown>
   8:           0x48d6a6 - <unknown>
   9:           0x40bde2 - <unknown>
  10:           0x42cadc - <unknown>
  11:           0x41185a - <unknown>
  12:           0x4203d5 - <unknown>
  13:           0x404544 - <unknown>
  14:           0x42e1bc - <unknown>
  15:           0x4013f8 - <unknown>
  16:           0x40151b - <unknown>
  17:     0x7ff89c177bd4 - <unknown>
  18:     0x7ff89cfcced1 - <unknown>`

**Comment by indocomsoft** [comment]
Can you try using this debug build?

[fluminurs.zip](https://github.com/indocomsoft/fluminurs/files/4089208/fluminurs.zip)

**Comment by ktkwon00** [comment]
Here is the output:

`fluminurs.exe --download-to "C:\tmp"
Hi (redacted)!
You are taking:
(redacted)
You are teaching:
Download to C:\tmp
Failed loading module files: Unable to deserialize JSON
thread 'main' panicked at 'Children should have been loaded', src\libcore\option.rs:1185:5
stack backtrace:
   0:     0x7ff70e007ca9 - <unknown>
   1:     0x7ff70e020fcb - <unknown>
   2:     0x7ff70e0017f4 - <unknown>
   3:     0x7ff70e00a7c9 - <unknown>
   4:     0x7ff70e00a41c - <unknown>
   5:     0x7ff70e00b01c - <unknown>
   6:     0x7ff70e00ab90 - <unknown>
   7:     0x7ff70e00aa79 - <unknown>
   8:     0x7ff70e01d6dd - <unknown>
   9:     0x7ff70e01d746 - <unknown>
  10:     0x7ff70d567dbd - <unknown>
  11:     0x7ff70d54283b - <unknown>
  12:     0x7ff70d4e36a2 - <unknown>
  13:     0x7ff70d4dd385 - <unknown>
  14:     0x7ff70d4e053b - <unknown>
  15:     0x7ff70d4dfd55 - <unknown>
  16:     0x7ff70d4d98d8 - <unknown>
  17:     0x7ff70d4df2d5 - <unknown>
  18:     0x7ff70d54717b - <unknown>
  19:     0x7ff70d4e3b82 - <unknown>
  20:     0x7ff70d4dcde5 - <unknown>
  21:     0x7ff70d4e029b - <unknown>
  22:     0x7ff70d4fe7f4 - <unknown>
  23:     0x7ff70d4e6eae - <unknown>
  24:     0x7ff70d4c5300 - <unknown>
  25:     0x7ff70d55ef7b - <unknown>
  26:     0x7ff70d52e1c5 - <unknown>
  27:     0x7ff70d4c5171 - <unknown>
  28:     0x7ff70d51f5ae - <unknown>
  29:     0x7ff70d549530 - <unknown>
  30:     0x7ff70e00a9d7 - <unknown>
  31:     0x7ff70e010212 - <unknown>
  32:     0x7ff70e00b242 - <unknown>
  33:     0x7ff70d54950b - <unknown>
  34:     0x7ff70d51f6a0 - <unknown>
  35:     0x7ff70e026594 - <unknown>
  36:     0x7ff89c177bd4 - BaseThreadInitThunk
  37:     0x7ff89cfcced1 - RtlUserThreadStart`

**Comment by indocomsoft** [comment]
Oops, I didn't build it correctly. Can you extract all the files from this zip and run? Hopefully the stack trace works now.

Also just wondering, are you taking FYP right now?

[fluminurs.zip](https://github.com/indocomsoft/fluminurs/files/4089426/fluminurs.zip)

**Comment by ktkwon00** [comment]
Nope, just a freshman.
Here's the output:

fluminurs.exe --download-to "C:\tmp"
Hi (redacted)!
You are taking:
(redacted)
You are teaching:
Download to C:\tmp
Failed loading module files: Unable to deserialize JSON
thread 'main' panicked at 'Children should have been loaded', src\libcore\option.rs:1185:5
stack backtrace:
   0:     0x7ff7a4af2739 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1:     0x7ff7a4af2739 - std::sys_common::backtrace::_print_fmt
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
   2:     0x7ff7a4af2739 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
   3:     0x7ff7a4b0b69b - core::fmt::write
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
   4:     0x7ff7a4aec384 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
   5:     0x7ff7a4af5219 - std::sys_common::backtrace::_print
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
   6:     0x7ff7a4af5219 - std::sys_common::backtrace::print
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
   7:     0x7ff7a4af5219 - std::panicking::default_hook::{{closure}}
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
   8:     0x7ff7a4af4e6c - std::panicking::default_hook
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
   9:     0x7ff7a4af5a6c - std::panicking::rust_panic_with_hook
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
  10:     0x7ff7a4af55e0 - std::panicking::continue_panic_fmt
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
  11:     0x7ff7a4af54c9 - std::panicking::rust_begin_panic
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:302
  12:     0x7ff7a4b07edd - core::panicking::panic_fmt
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:139
  13:     0x7ff7a4b07f46 - core::option::expect_failed
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\option.rs:1185
  14:     0x7ff7a47a368e - fluminurs::main::{{closure}}::h2053a7e9c6dd8dcd
  15:     0x7ff7a47b459e - tokio::runtime::enter::Enter::block_on::hdba360b40430d86c
  16:     0x7ff7a47efc7f - tokio::runtime::context::enter::h01c2735547c8f0cd
  17:     0x7ff7a47b4800 - tokio::runtime::handle::Handle::enter::h5f057b17ad1c2f0d
  18:     0x7ff7a4788f90 - fluminurs::store_credentials::h0fd64c7f7e4316cf
  19:     0x7ff7a47e9216 - std::io::Read::read_to_string::heb9362f27696a7af
  20:     0x7ff7a4af5427 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:48
  21:     0x7ff7a4af5427 - std::panicking::try::do_call<closure-0,i32>
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:287
  22:     0x7ff7a4afac42 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
  23:     0x7ff7a4af5c92 - std::panicking::try
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:265
  24:     0x7ff7a4af5c92 - std::panic::catch_unwind
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panic.rs:396
  25:     0x7ff7a4af5c92 - std::rt::lang_start_internal
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:47
  26:     0x7ff7a4789137 - main
  27:     0x7ff7a4b10af4 - invoke_main
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  28:     0x7ff7a4b10af4 - __scrt_common_main_seh
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  29:     0x7ff89c177bd4 - BaseThreadInitThunk
  30:     0x7ff89cfcced1 - RtlUserThreadStart

**Comment by indocomsoft** [comment]
Ah, right. That is probably why. Can you try the release I just made? https://github.com/indocomsoft/fluminurs/releases/tag/1.1.5

Someone else experienced that problem. Hopefully this is the real fix

**Comment by ktkwon00** [comment]
It works now, thank you!
