### ISSUE TITLE
Updated files are not re-downloaded

### ISSUE THREAD

**Issue by btzy** [indocomsoft/fluminurs#52]
When a file is updated on Luminus, fluminurs does not re-download the file, and also does not give any warning.  This is a problem, because to get all updated files, users have to clear the local directory and re-run fluminurs.

I'm not sure about the API specifics, but Luminus does display a "Last Modified" date in its user interface, and that might be usable by fluminurs.

Note: In practice, some lecturers delete the old file before re-uploading the new version to Luminus.  So the "Created" date probably should be ignored.

**Comment by angelsl** [comment]
I'll implement this I guess, when I have a bit of time.

I'll probably have it warn you if a file's last-modified time is newer by default, and have a flag to tell it to overwrite files if they are newer.

**Comment by indocomsoft** [comment]
I think we might also want some flag to not overwrite, but instead rename the old file before downloading the new one.
