### ISSUE TITLE
Move to std::future and async/await

### ISSUE THREAD

**Issue by goweiwen** [indocomsoft/fluminurs#70]
Since `async` is now in the beta channel, and our dependencies (`tokio`, `reqwest`) have been updated to use them, we should look to migrate to using it.

I can work on this if it sounds good.

**Comment by indocomsoft** [comment]
Yeah, feel free!

**Comment by angelsl** [comment]
Let's release a new fluminurs when 1.39 drops on 7 Nov. That'd be cool. :joy:

**Comment by angelsl** [comment]
Anyway, let me know if you need any help.

The old-style futures get really verbose when you start having complex combinators and stuff and then you have to sprinkle `Either` here and there. I'm glad we're moving away from that, finally.
